agromaps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('map/', include('map.urls')),
    path('', include('main.urls')),
    path('authentication/', include('authentication.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

map/urls.py
from django.urls import path
from . import views
from .views import FieldsListView, CultureListView, SeedListView, SeedView, FieldView, CultureView

app_name = 'map'
urlpatterns = [
    path('', views.index, name='index'),
    #Field routes
    path('fields/', views.fields, name='fields'),
    path('fields/map/', FieldsListView.as_view(), name='map-api'),
    #Culture routes
    path('cultures/', views.cultures, name='cultures'),
    path('cultures/<int:culture_id>/edit/', CultureView.as_view(), name='culture_edit'),
     path('new_culture/', CultureView.as_view(), name='culture_new'),

    path('<int:seed_id>/', views.detail, name='detail'),
    path('new_seed/', SeedView.as_view(), name='seed_new'),
    path('fields/<int:seed_id>/edit/', SeedView.as_view(), name='seed_edit'),

    path('new_field/', FieldView.as_view(), name='field_new'),
    path('new_field/map/', FieldsListView.as_view(), name='map-api'),
    path('map/', FieldsListView.as_view(), name='map-api'),
    path('culture/', CultureListView.as_view(), name='culture-api'),
    path('seed/', SeedListView.as_view(), name='seed-api'),
    path('new_seed/map/', FieldsListView.as_view(), name='map-api'),
    path('new_seed/culture/', CultureListView.as_view(), name='culture-api'),
    path('new_seed/seed/', SeedListView.as_view(), name='seed-api')
]

map/models.py
from django.db import models

# Create your models here.

#Процес
class Process(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return(self.name)

#Агро культура
class Culture(models.Model):
    name = models.CharField(max_length=9)
    color = models.CharField(max_length=7, default="#cccccc")

    #Отображение названия модели в админке
    def __str__(self):
        return(self.name)
    
#Поле
class Field(models.Model):
    title = models.CharField(max_length=16)
    square = models.FloatField()
    polygon =  models.CharField(max_length=256, default="")

    #Отображение названия модели в админке
    def __str__(self):
        return (self.title)

#Посів поля
class SeedProcess(models.Model):
    seedDate = models.DateField()
    harvestDate = models.DateField()
    field = models.ForeignKey(Field,default=1, on_delete=models.CASCADE)
    culture =  models.ForeignKey(Culture, default=1, on_delete=models.CASCADE)

    def __str__(self):
        return(str(self.seedDate))

map/forms.py
from django import forms
from .models import Field, Culture, SeedProcess
from django.forms.widgets import TextInput

class SeedForm(forms.ModelForm):
    seedDate = forms.DateField(widget = forms.DateInput(attrs={'type': 'date'}), label='Дата посіву')
    harvestDate = forms.DateField(widget = forms.DateInput(attrs={'type': 'date'}), label='Очікувана дата збору')
    field = forms.ModelChoiceField(queryset= Field.objects.all(), label='Поле')
    culture = forms.ModelChoiceField(queryset= Culture.objects.all(), label='Культура')

    class Meta:
        model = SeedProcess
        fields = ['seedDate', 'harvestDate', 'field', 'culture']

class FieldForm(forms.ModelForm):
    title = forms.CharField(max_length=16, label='Назва')
    square = forms.FloatField(required=False, label='Площа')
    polygon = forms.CharField(max_length=256, label='Контур')

    class Meta:
        model = Field
        fields = ['title', 'polygon', 'square']

class CultureForm(forms.ModelForm):
    name = forms.CharField(max_length=32, label='Назва')
    class Meta:
        model = Culture
        fields = ['name', 'color']
        widgets = {
            'color': TextInput(attrs={'type': 'color'}),
        }
        
		

map/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Field, Culture, Process, SeedProcess
from rest_framework import generics
from rest_framework.permissions import IsAdminUser, IsAuthenticated
from .serializers import  FieldSerializer, CultureSerializer, SeedSerializer

from django.views import View
from .forms import SeedForm, FieldForm, CultureForm
from django.http import HttpResponseRedirect


@login_required
def index(request):

    seeds = SeedProcess.objects.all()
    fields = []
    for seed in seeds:
    	fields.append(Field.objects.get(pk=seed.field.pk))
    	
    context = {
    	'seeds' : seeds,
        'fields' : fields
    }
    
    return render(request, 'map/index.html', context)

@login_required
def detail(request, seed_id):
    seed = get_object_or_404(SeedProcess, pk=seed_id)
    field = get_object_or_404(Field, pk=seed.field.pk)
    culture = get_object_or_404(Culture, pk=seed.culture.pk)

    context = {
        'seed' : seed,
        'field' : field,
        'culture' : culture,
    }

    return render(request, 'map/seed_detail.html', context)

@login_required
def fields(request):
  
    fields = Field.objects.all()

    context = {
        'fields' : fields
    }

    return render(request, 'map/fields.html', context)

@login_required
def cultures(request):
    cultures = Culture.objects.all()

    context = {
        'cultures' : cultures
    }

    return render(request, 'map/cultures.html', context)

class FieldsListView(generics.ListAPIView):
    """docstring for FieldsListView"""
    lookup_field = 'pk'
    queryset = Field.objects.all()
    serializer_class = FieldSerializer
    permission_classes = (IsAuthenticated,)
		
class CultureListView(generics.ListAPIView):
	lookup_field = 'pk'
	queryset = Culture.objects.all()
	serializer_class = CultureSerializer
	permission_classes = (IsAuthenticated,)

class SeedListView(generics.ListAPIView):
    lookup_field = 'pk'
    queryset = SeedProcess.objects.all()
    serializer_class = SeedSerializer
    permission_classes = (IsAuthenticated,)

class SeedView(View):
    decorators = [login_required]
    
    @method_decorator(decorators)
    def get(self, request, id=None, seed_id=None):  
        if id != None or seed_id != None:
            seed = get_object_or_404(SeedProcess, pk=seed_id)
            seed_form = SeedForm(instance=seed)
            template = 'seed_edit.html'
        else:
            seed_form = SeedForm(instance=SeedProcess())
            template = 'seed_new.html'
        context = {'seed_form': seed_form}
        return render(request, template, context)

    @method_decorator(decorators)
    def post(self, request, id=None, seed_id=None):
        context = {}
        method = self.request.POST.get('_method', '').lower()
        print(method)
        if id != None or seed_id != None:
            if method == 'put':
                return self.put(request, id, seed_id)
            elif method == 'delete':
                return self.delete(request, id)
        seed_form = SeedForm(request.POST, instance=SeedProcess())
        if seed_form.is_valid():
            new_seed = seed_form.save(commit=False)
            new_seed.save()
            return HttpResponseRedirect('/map/')
        context = {'seed_form' : seed_form}
        return render(request, 'seed_new.html', context)

    @method_decorator(decorators)
    def put(self, request, id=None, seed_id= None):
        context = {}
        print('put field')
        seed = get_object_or_404(SeedProcess, pk=seed_id)
        seed_form = SeedForm(request.POST, instance=seed)
        if seed_form.is_valid():
            new_seed = seed_form.save(commit=False)
            new_seed.save()
            return HttpResponseRedirect('/map/')
        context = {'seed_form' : seed_form}
        return render(request, 'seed_edit.html', context) 

    # def delete(self, request, id=None):
    #     post = get_object_or_404(Post, pk=id)
    #     post_form = DeletePostForm(request.POST, instance=post)
    #     if post_form.is_valid():
    #         post.delete()
    #         return HttpResponseRedirect('/news/')
    #     return render(request, 'post_delete.html', {})

class FieldView(View):
    decorators = [login_required]
    
    @method_decorator(decorators)
    def get(self, request, id=None, field_id=None):  
        if id != None or field_id != None:
            field = get_object_or_404(Field, pk=field_id)
            field_form = FieldForm(instance=field)
            template = 'field_edit.html'
        else:
            field_form = FieldForm(instance=Field())
            template = 'field_new.html'
        context = {'field_form': field_form}
        return render(request, template, context)

    @method_decorator(decorators)
    def post(self, request, id=None):
        context = {}
        method = self.request.POST.get('_method', '').lower()
        print(method)
        if id != None:
            if method == 'put':
                return self.put(request, id)
            elif method == 'delete':
                return self.delete(request, id)
        field_form = FieldForm(request.POST, instance=Field())
        if field_form.is_valid():
            new_field = field_form.save(commit=False)
            new_field.save()
            return HttpResponseRedirect('/map/fields/')
        context = {'field_form' : field_form}
        return render(request, 'field_new.html', context)

    @method_decorator(decorators)
    def put(self, request, id=None):
        context = {}
        print('put field')
        seed = get_object_or_404(Seed, pk=id)
        seed_form = SeedForm(request.POST, instance=seed)
        if seed_form.is_valid():
            new_seed = post_form.save(commit=False)
            new_seed.save()
            return HttpResponseRedirect('/map/')
        context = {'seed_form' : seed_form}
        return render(request, 'seed_edit.html', context)	

class CultureView(View):
    decorators = [login_required]
    
    @method_decorator(decorators)
    def get(self, request, id=None, culture_id=None):  
        if id != None or culture_id != None:
            culture = get_object_or_404(Culture, pk=culture_id)
            culture_form = CultureForm(instance=culture)
            template = 'culture_edit.html'
        else:
            culture_form = CultureForm(instance=Culture())
            template = 'culture_new.html'
        context = {'culture_form': culture_form}
        return render(request, template, context)

    @method_decorator(decorators)
    def post(self, request, id=None, culture_id=None):
        context = {}
        method = self.request.POST.get('_method', '').lower()
        if id != None or culture_id != None:
            print(method)
            if method == 'put':
                return self.put(request, culture_id)
            elif method == 'delete':
                return self.delete(request, id)
        culture_form = CultureForm(request.POST, instance=Culture())
        if culture_form.is_valid():
            new_culture = culture_form.save(commit=False)
            new_culture.save()
            return HttpResponseRedirect('/map/cultures/')
        context = {'culture_form' : culture_form}
        return render(request, 'culture_new.html', context)

    @method_decorator(decorators)
    def put(self, request, id=None):
        context = {}
        culture = get_object_or_404(Culture, pk=id)
        culture_form = CultureForm(request.POST, instance=culture)
        if culture_form.is_valid():
            new_culture = culture_form.save(commit=False)
            new_culture.save()
            return HttpResponseRedirect('/map/cultures/')
        context = {'culture_form' : culture_form}
        return render(request, 'culture_edit.html', context)   

map/templates/map/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Crops Online | Map overview</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

		{% load staticfiles %}
		<link rel="stylesheet" href="{% static 'map/css/style.css' %}" type="text/css">

	</head>
	<body>
		<!-- WRAPPER -->
		<div id="wrapper">
			<!-- SIDEBAR -->
			<div id="sidebar-wrapper">
				<div id="toggle-btn">
					<i class="fas fa-bars"></i>
				</div>
				<ul class="sidebar-nav">
					<div class="toggle-place"></div>
					<li id="sidebar-nav-li"><a href="/" class="sidebar-toggle">
						<h6 class="eve-header">crops<br>online</h6></a>
					</li>
					{% if user.is_authenticated %}
						<li id="sidebar-nav-li">
							<a class="colored-link" href="#"><i class="fas fa-user-tie"></i><br>{{ user.get_username }}</a>
						</li>

						{% block navbar %}
						{% endblock %}
					{% endif %}

				</ul>
			</div>

			<!-- PAGE CONTENT -->
			<div id="page-content-wrapper">
				<!--BOOTSTRAP -->
				<div class="container-fluid page">
					<div class="row">
						<div class="col-lg-12">
							<div class="page-content">
								{% block pageContent %}
								{% endblock %}
							</div>
						</div>
					</div>
				</div>
			</div>
	    </div>
	</body>

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	{% block loadscript %}
  	{% endblock %}

</html>

map/templates/map/culture_edit.html
{% extends "map/base.html" %}

{% block pageContent %}
	<div class="row">
		<div class="col">
		</div>
		<div class="col-3">
			<div class="window-block">
				<div class="window-block-head">
					<p>Редагувати культуру</p>
				</div>
				<form method="POST">
					<div class="window-block-body">
						<div class="table-container">
							{% csrf_token %}
							<table class="table table-bordered table-dark">
								{{culture_form.as_table}}
							</table>
						</div>
						<center>
							<button type="submit" class="co-button" name="_method" value="put">
								<i class="fas fa-plus"></i>
								Зберегти
							</button>
						</center>
					</div>
				</form>
			</div>
		</div>
		<div class="col">
		</div>
	</div>
{% endblock %}	

{% block loadscript %}
	{% load static %}
	<script type="text/javascript" src="{% static 'map/js/cultures.js' %}"></script>
{% endblock %}

map/templates/map/culture_new.html
{% extends "map/base.html" %}

{% block pageContent %}
	<div class="row">
		<div class="col">
		</div>
		<div class="col-3">
			<div class="window-block">
				<div class="window-block-head">
					<p>Нова культура</p>
				</div>
				<form method="POST">
					<div class="window-block-body">
						<div class="table-container">
							{% csrf_token %}
							<table class="table table-bordered table-dark">
								{{culture_form.as_table}}
							</table>
						</div>
						<center>
							<button type="submit" class="co-button">
								<i class="fas fa-plus"></i>
								Додати
							</button>
						</center>
					</div>
				</form>
			</div>
		</div>
		<div class="col">
		</div>
	</div>
{% endblock %}	

{% block loadscript %}
	{% load static %}
	<script type="text/javascript" src="{% static 'map/js/cultures.js' %}"></script>
{% endblock %}

map/templates/map/cultures.html
{% extends "map/base.html" %}

{% block navbar %}
	<li id="sidebar-nav-li">
		<a href="/map/"><i class="fas fa-map"></i><br>Карта поcівів</a>
	</li>
{% endblock %}

{% block pageContent %}
	<div class="row">
		<div class="col"></div>
		<div class="col-8">
			<div class="window-block">
				<div class="window-block-head">
					<p>Журнал обліку культур</p>
				</div>
				<div class="window-block-body">
					<div class="table-container">
						<table>
							<thead>
								<tr>
									<th>Назва</th><th>Колір</th><th>Дія</th>
								</tr>
							</thead>
							<tbody>
								{% for culture in cultures %}
									<tr>
										<td>
											<p>{{ culture.name }}</p>	
										</td>
										<td>
											<p><i class="fas fa-square-full" style="color: {{ culture.color }};"></i> 
										</td>
										<td>
											<a href="{% url 'map:culture_edit' culture.id %}"><i class="fas fa-edit"></i> Редагувати</a>
										</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
					<center>
						<button type="submit" class="co-button" >
							<i class="fas fa-plus"></i>
							<a href="/map/new_culture/">Додати нову культуру</a>
						</button>
					</center>
				</div>
			</div>
		</div>
		<div class="col"></div>
	</div>
{% endblock %}	

{% block loadscript %}
	{% load static %}
	<script type="text/javascript" src="{% static 'map/js/cultures.js' %}"></script>
{% endblock %}

map/templates/map/field_detail.html
{% extends "map/index.html" %}

{% block pageContent %}
		<h4>{{field.title}}</h4>
		<p>Площа: {{field.square}}</p>
		<p>Посадженно: {{culture.name}}</p>
		<p>Процес: {{process.name}}</p>
{% endblock %}

map/templates/map/field_new.html
{% extends "map/base.html" %}

{% block pageContent %}
	<div class="row">
		<div class="col-9">
			<!-- MAP -->
			<div class="window-block">
				<div class="window-block-head">
					<p>Карта полів</p>
				</div>
				<div class="window-block-body">
					<div id="map"></div>
				</div>
			</div>
		</div>
		<div class="col-3">
			<div class="window-block">
				<div class="window-block-head">
					<p>Нове поле</p>
				</div>
				<form method="POST">
					<div class="window-block-body">
						<div class="table-container">
							{% csrf_token %}
							<table class="table table-bordered table-dark">
								{{field_form.as_table}}
							</table>
						</div>
						<center>
							<button type="submit" class="co-button">
								<i class="fas fa-plus"></i>
								Додати
							</button>
						</center>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}	

{% block loadscript %}
	{% load static %}
	<script type="text/javascript" src="{% static 'map/js/fieldEdit.js' %}"></script>

	<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC0Awqy1JqMvPwazWB-H90j9CRm6vuWN-4&callback=initMap"
  	type="text/javascript">
	</script>
{% endblock %}

map/templates/map/fields.html
{% extends "map/index.html" %}

{% block content %}
	{% for field in fields %}
					<button class="accordion">{{field.title}}</button>
					<div class="panel">
	  					<p>
	  						
	  					</p>
					</div>
	{% endfor %}
{% endblock %}

map/templates/map/index.html
{% extends "map/base.html" %}

{% block navbar %}
	<li id="sidebar-nav-li">
		<a href="/map/fields/"><i class="fas fa-map"></i><br>Журнал полів</a>
	</li>
	<li id="sidebar-nav-li">
		<a href="/map/cultures/"><i class="fas fa-clipboard-list"></i><br>Журнал культур</a>
	</li>
{% endblock %}

{% block pageContent %}
	<div class="row">
		<div class="col-8">
			<!-- MAP -->
			<div class="window-block">
				<div class="window-block-head">
					<p>Карта посівів</p>
				</div>
				<div class="window-block-body">
					<div id="map"></div>
				</div>
			</div>
		</div>
		<div class="col-4">
			<div class="window-block">
				<div class="window-block-head">
					<p>Журнал обліку посівів</p>
				</div>
				<div class="window-block-body">
					<div class="table-container">
						<table>
							<thead>
								<tr>
									<th>Дата посіву</th>
									<th>Культура</th>
									<th>Дія</th>	
								</tr>
							</thead>
							<tbody>
								{% for seed in seeds %}
									<tr>
										<td>
											<a href="{% url 'map:detail' seed.id %}">{{ seed.seedDate }}</a>	
										</td>
										<td>
											<p href="{% url 'map:detail' seed.id %}"><i class="fas fa-square-full" style="color: {{ seed.culture.color }};"></i> {{seed.culture }}</p>	

										</td>
										<td>
											<a href="{% url 'map:seed_edit' seed.id %}"><i class="fas fa-edit"></i> </a>
										</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
					<center>
						<button type="submit" class="co-button" >
							<i class="fas fa-edit"></i> 
							<a href="/map/new_seed/">Додати новий посів</a>
						</button>
					</center>
				</div>
			</div>
		</div>
	</div>
{% endblock %}	

{% block loadscript %}
	{% load static %}
	<script type="text/javascript" src="{% static 'map/js/map.js' %}"></script>

	<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC0Awqy1JqMvPwazWB-H90j9CRm6vuWN-4&callback=initMap"
  	type="text/javascript">
	</script>
{% endblock %}

map/templates/map/seed_detail.html
{% extends "map/base.html" %}

{% block pageContent %}
	<div class="row">
		<div class="col-9">
			<!-- MAP -->
			<div class="window-block">
				<div class="window-block-head">
					<p>Карта полів</p>
				</div>
				<div class="window-block-body">
					<div id="map"></div>
				</div>
			</div>
		</div>
		<div class="col-3">
			<div class="window-block">
				<div class="window-block-head">
					<p>Інформація про посів</p>
				</div>
				<div class="window-block-body">
					<div class="table-container">
						<table>
							<tbody>
								<tr><td>Дата посіву</td><td class="orange-text">{{ seed.seedDate }}</td></tr>
								<tr><td>Очікувана дата збору</td><td class="orange-text">{{ seed.harvestDate }}</td></tr>
								<tr><td>Культура</td><td class="orange-text">{{ culture.name }}</td></tr>
								<tr><td>Поле</td><td class="orange-text">{{ field.title }}</td></tr>
							</tbody>
						</table>	
					</div>
					<div class="row">
						<div class="col-8">
							<center>
							<button type="submit" class="co-button">
								<i class="fas fa-edit"></i> 
								<a href="/map/edit_seed/" name="_method" value="put">Редагувати</a>
							</button>
							</center>
						</div>
						<div class="col-4">
							<center>
							<button type="submit" class="co-button">
							<a href="/map/delete_seed/" name="_method" value="delete"><i class="fas fa-trash-alt"></i></a>
							</center>
						</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}	

{% block loadscript %}
	{% load static %}
	<script type="text/javascript" src="{% static 'map/js/map.js' %}"></script>

	<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC0Awqy1JqMvPwazWB-H90j9CRm6vuWN-4&callback=initMap"
  	type="text/javascript">
	</script>
{% endblock %}

map/templates/map/seed_edit.html
{% extends "map/base.html" %}

{% block pageContent %}
	<div class="row">
		<div class="col-9">
			<!-- MAP -->
			<div class="window-block">
				<div class="window-block-head">
					<p>Карта полів</p>
				</div>
				<div class="window-block-body">
					<div id="map"></div>
				</div>
			</div>
		</div>
		<div class="col-3">
			<div class="window-block">
				<div class="window-block-head">
					<p>Редагувати посів</p>
				</div>
				<form method="POST">
					<div class="window-block-body">
						<div class="table-container">
							{% csrf_token %}
							<table class="table table-bordered table-dark">
								{{seed_form.as_table}}
							</table>
						</div>
						<button type="submit" class="co-button" name="_method" value="put">
						<i class="fas fa-save"></i>
						Оновити
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}	

{% block loadscript %}
	{% load static %}
	<script type="text/javascript" src="{% static 'map/js/map.js' %}"></script>

	<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC0Awqy1JqMvPwazWB-H90j9CRm6vuWN-4&callback=initMap"
  	type="text/javascript">
	</script>
{% endblock %}

map/templates/map/seed_new.html
{% extends "map/base.html" %}

{% block pageContent %}
	<div class="row">
		<div class="col-9">
			<!-- MAP -->
			<div class="window-block">
				<div class="window-block-head">
					<p>Карта полів</p>
				</div>
				<div class="window-block-body">
					<div id="map"></div>
				</div>
			</div>
		</div>
		<div class="col-3">
			<div class="window-block">
				<div class="window-block-head">
					<p>Новий посів</p>
				</div>
				<form method="POST">
					<div class="window-block-body">
						<div class="table-container">
							{% csrf_token %}
							<table class="table table-bordered table-dark">
								{{seed_form.as_table}}
							</table>
						</div>
						<center>
							<button type="submit" class="co-button">
								<i class="fas fa-save"></i>
								Додати
							</button>
						</center>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}	

{% block loadscript %}
	{% load static %}
	<script type="text/javascript" src="{% static 'map/js/map.js' %}"></script>

	<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC0Awqy1JqMvPwazWB-H90j9CRm6vuWN-4&callback=initMap"
  	type="text/javascript">
	</script>
{% endblock %}